# Generated by Django 4.0.4 on 2022-04-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='owners',
            field=models.BigIntegerField(null=True, verbose_name='number of owners'),
        ),
        migrations.AlterField(
            model_name='games',
            name='rel_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='release_date'),
        ),
    ]
