# Generated by Django 4.0.4 on 2022-04-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='achievements',
            field=models.BigIntegerField(null=True, verbose_name='number of Achievements'),
        ),
        migrations.AlterField(
            model_name='games',
            name='avg_playtime',
            field=models.BigIntegerField(null=True, verbose_name='average_playtime'),
        ),
        migrations.AlterField(
            model_name='games',
            name='categories',
            field=models.CharField(max_length=255, null=True, verbose_name='categeories'),
        ),
        migrations.AlterField(
            model_name='games',
            name='english',
            field=models.CharField(max_length=1, null=True, verbose_name=('in english',)),
        ),
        migrations.AlterField(
            model_name='games',
            name='median_playtime',
            field=models.BigIntegerField(null=True, verbose_name='median_playtime'),
        ),
        migrations.AlterField(
            model_name='games',
            name='neg_rate',
            field=models.BigIntegerField(null=True, verbose_name='negative_ratings'),
        ),
        migrations.AlterField(
            model_name='games',
            name='owners',
            field=models.BigIntegerField(null=True, verbose_name='number of owners'),
        ),
        migrations.AlterField(
            model_name='games',
            name='platform',
            field=models.CharField(max_length=150, null=True, verbose_name='platforms'),
        ),
        migrations.AlterField(
            model_name='games',
            name='pos_rate',
            field=models.BigIntegerField(null=True, verbose_name='positive_ratings'),
        ),
        migrations.AlterField(
            model_name='games',
            name='rec_age',
            field=models.CharField(max_length=155, null=True, verbose_name='required Age'),
        ),
        migrations.AlterField(
            model_name='games',
            name='rel_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='release_date'),
        ),
        migrations.AlterField(
            model_name='games',
            name='steamspy_tags',
            field=models.CharField(max_length=250, null=True, verbose_name='steamspy tags'),
        ),
    ]
