# Generated by Django 4.0.4 on 2022-04-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_alter_games_achievements_alter_games_avg_playtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='gameid',
            field=models.IntegerField(null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='games',
            name='owners',
            field=models.CharField(max_length=100, null=True, verbose_name='number of owners'),
        ),
    ]
