# Generated by Django 4.0.3 on 2022-05-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_alter_games_achievements_alter_games_avg_playtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='owners',
            field=models.CharField(max_length=100, null=True, verbose_name='number of owners'),
        ),
    ]
