# Generated by Django 4.0.4 on 2022-04-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_games_gameid_alter_games_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='gameid',
            new_name='game_id',
        ),
    ]
