# Generated by Django 4.0.4 on 2022-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0004_rename_gameid_games_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_id',
            field=models.BigIntegerField(null=True, verbose_name='id'),
        ),
    ]
